import "./global.css";
import { Footer } from "./components/footer";
import { Header } from "./components/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className="bg-roseGray">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
